export * from './main.component'
export * from './watch-list/watch-list.component'
export * from './search/search.component'
export * from './home/home.component'
export * from './movie-details/movie-details.component'